### ISSUE TITLE
Unable to test the code

### ISSUE THREAD

**Issue by Brahmagupta** [csyanbin/SCOT#9]
There might be changes in Pytorch that makes the code fail to work.
After I fixed the #8 dataset downloading issue, I try to test SCOT on PF-PASCAL by running 

```
python evaluate_map_CAM.py --dataset pfpascal --thres img --backbone resnet101 --hyperpixel '(2,22,24,25,27,28,29)' --sim OTGeo --exp1 1.0 --exp2 0.5 --eps 0.05 --gpu 0 --classmap 1 --split test --alpha 0.05
```
As instructed in the README.md. 
The Error I got is 
```
Traceback (most recent call last):
  File "evaluate_map_CAM.py", line 137, in <module>
    alpha=args.alpha, hyperpixel=args.hyperpixel, logpath=args.logpath, args=args, beamsearch=False)

  File "evaluate_map_CAM.py", line 78, in run
    confidence_ts, src_box, trg_box = model(data['src_img'], data['trg_img'], args.sim, args.exp1, args.exp2, args.eps, args.classmap, data['src_bbox'], data['trg_bbox'], data['src_mask'], data['trg_mask'], backbone)

  File "TestSCOT/SCOT/model/scot_CAM.py", line 70, in __call__
    src_hyperpixels = self.extract_hyperpixel(args[0], maptype, src_bbox, src_mask, backbone)

  File "TestSCOT/SCOT/model/scot_CAM.py", line 79, in extract_hyperpixel
    hpgeometry = geometry.receptive_fields(rfsz, jsz, hyperfeats.size()).to(self.device)

  File "TestSCOT/SCOT/model/geometry.py", line 24, in receptive_fields
    box[:, 0] = feat_ids[:, 1] * jsz - rfsz // 2

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

I know tensors supposed to be on GPU while arrays on CPU. But I'm kinda new to this, I wonder if any idea how I can fix this.

**What I did** 
1. Delete the .to(self.device) on line 79 in ./model/scot_CAM.py.   
      ----- Still the same Error
2. Test the model on a CPU only machine   
      ----- Another Error says that some tensor manipulations need to be done with cuda, requiring a GPU access

**Comment by Brahmagupta** [comment]
Actually there's something wrong with Floor Division : //

```
/SCOT/model/geometry.py:24: UserWarning: __floordiv__ is deprecated, 
and its behavior will change in a future version of pytorch.
It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). 
This results in incorrect rounding for negative values. To keep the current behavior,
use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, 
use torch.div(a, b, rounding_mode='floor').

  box[:, 0] = feat_ids[:, 1] * jsz - rfsz // 2
```
But when I replace all // operations with torch.div(, , rounding_mode = 'floor').

I'm still getting the "Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!" Error

**Comment by Brahmagupta** [comment]
The problem might be with the line 24 in receptive_fields method in File "model/geometry.py".
```
box[:, 0] = feat_ids[:, 1] * jsz - rfsz // 2
```
it seems like both box and feat_ids are created to be on CPU but jsz and rfsz are initialized in "model/SCOT_CAM.py" on CUDA

**Comment by Brahmagupta** [comment]
Found the fix:
in line 20 in in receptive_fields method in File "model/geometry.py".
Add .to('cuda') or .cuda() to the definition of feat_ids, i.e.
```
feat_ids = torch.tensor(list(range(width))).repeat(1, height).t().repeat(1, 2).to('cuda')
```

So over all two lines need to be changed (along with #8)

**Comment by Brahmagupta** [comment]
By the way, if possible could you pls provide the full output of 
```
conda list -n scot
```
Thanks in advance
